require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'plaidRNDemo' do
  pod 'Plaid', '~> 2' # Always use the most up to date version within major version 2.
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'plaidRNDemoTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'plaidRNDemo-tvOS' do
  # Pods for plaidRNDemo-tvOS

  target 'plaidRNDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
