export var LinkLogLevel;
(function (LinkLogLevel) {
    LinkLogLevel[LinkLogLevel["DEBUG"] = 0] = "DEBUG";
    LinkLogLevel[LinkLogLevel["INFO"] = 1] = "INFO";
    LinkLogLevel[LinkLogLevel["WARN"] = 2] = "WARN";
    LinkLogLevel[LinkLogLevel["ERROR"] = 3] = "ERROR";
})(LinkLogLevel || (LinkLogLevel = {}));
export var PlaidEnvironment;
(function (PlaidEnvironment) {
    PlaidEnvironment["PRODUCTION"] = "production";
    PlaidEnvironment["DEVELOPMENT"] = "development";
    PlaidEnvironment["SANDBOX"] = "sandbox";
})(PlaidEnvironment || (PlaidEnvironment = {}));
export var PlaidProduct;
(function (PlaidProduct) {
    PlaidProduct[PlaidProduct["ASSETS"] = 0] = "ASSETS";
    PlaidProduct[PlaidProduct["AUTH"] = 1] = "AUTH";
    PlaidProduct[PlaidProduct["IDENTITY"] = 2] = "IDENTITY";
    PlaidProduct[PlaidProduct["INCOME"] = 3] = "INCOME";
    PlaidProduct[PlaidProduct["INVESTMENTS"] = 4] = "INVESTMENTS";
    PlaidProduct[PlaidProduct["LIABILITIES"] = 5] = "LIABILITIES";
    PlaidProduct[PlaidProduct["LIABILITIES_REPORT"] = 6] = "LIABILITIES_REPORT";
    PlaidProduct[PlaidProduct["PAYMENT_INITIATION"] = 7] = "PAYMENT_INITIATION";
    PlaidProduct[PlaidProduct["TRANSACTIONS"] = 8] = "TRANSACTIONS";
})(PlaidProduct || (PlaidProduct = {}));
export var LinkAccountType;
(function (LinkAccountType) {
    LinkAccountType["CREDIT"] = "credit";
    LinkAccountType["DEPOSITORY"] = "depository";
    LinkAccountType["INVESTMENT"] = "investment";
    LinkAccountType["LOAN"] = "loan";
    LinkAccountType["OTHER"] = "other";
})(LinkAccountType || (LinkAccountType = {}));
export var LinkAccountSubtype;
(function (LinkAccountSubtype) {
    LinkAccountSubtype["CREDIT_CARD"] = "credit card";
    LinkAccountSubtype["PAYPAL"] = "paypal";
    LinkAccountSubtype["AUTO"] = "auto";
    LinkAccountSubtype["BUSINESS"] = "business";
    LinkAccountSubtype["COMMERCIAL"] = "commercial";
    LinkAccountSubtype["CONSTRUCTION"] = "construction";
    LinkAccountSubtype["CONSUMER"] = "consumer";
    LinkAccountSubtype["HOME_EQUITY"] = "home equity";
    LinkAccountSubtype["LINE_OF_CREDIT"] = "line of credit";
    LinkAccountSubtype["LOAN"] = "loan";
    LinkAccountSubtype["MORTGAGE"] = "mortgage";
    LinkAccountSubtype["OVERDRAFT"] = "overdraft";
    LinkAccountSubtype["STUDENT"] = "student";
    LinkAccountSubtype["CASH_MANAGEMENT"] = "cash management";
    LinkAccountSubtype["CD"] = "cd";
    LinkAccountSubtype["CHECKING"] = "checking";
    LinkAccountSubtype["EBT"] = "ebt";
    LinkAccountSubtype["HSA"] = "hsa";
    LinkAccountSubtype["MONEY_MARKET"] = "money market";
    LinkAccountSubtype["PREPAID"] = "prepaid";
    LinkAccountSubtype["SAVINGS"] = "savings";
    LinkAccountSubtype["FOUR_0_1_A"] = "401a";
    LinkAccountSubtype["FOUR_0_1_K"] = "401k";
    LinkAccountSubtype["FOUR_0_3_B"] = "403B";
    LinkAccountSubtype["FOUR_5_7_B"] = "457b";
    LinkAccountSubtype["FIVE_2_9"] = "529";
    LinkAccountSubtype["BROKERAGE"] = "brokerage";
    LinkAccountSubtype["CASH_ISA"] = "cash isa";
    LinkAccountSubtype["EDUCATION_SAVINGS_ACCOUNT"] = "education savings account";
    LinkAccountSubtype["FIXED_ANNUNITY"] = "fixed annuity";
    LinkAccountSubtype["GIC"] = "gic";
    LinkAccountSubtype["HEALTH_REIMBURSEMENT_ARRANGEMENT"] = "health reimbursement arrangement";
    LinkAccountSubtype["IRA"] = "ira";
    LinkAccountSubtype["ISA"] = "isa";
    LinkAccountSubtype["KEOGH"] = "keogh";
    LinkAccountSubtype["LIF"] = "lif";
    LinkAccountSubtype["LIRA"] = "lira";
    LinkAccountSubtype["LRIF"] = "lrif";
    LinkAccountSubtype["LRSP"] = "lrsp";
    LinkAccountSubtype["MUTUAL_FUND"] = "mutual fund";
    LinkAccountSubtype["NON_TAXABLE_BROKERAGE_ACCOUNT"] = "non-taxable brokerage account";
    LinkAccountSubtype["PENSION"] = "pension";
    LinkAccountSubtype["PLAN"] = "plan";
    LinkAccountSubtype["PRIF"] = "prif";
    LinkAccountSubtype["PROFIT_SHARING_PLAN"] = "profit sharing plan";
    LinkAccountSubtype["RDSP"] = "rdsp";
    LinkAccountSubtype["RESP"] = "resp";
    LinkAccountSubtype["RETIREMENT"] = "retirement";
    LinkAccountSubtype["RLIF"] = "rlif";
    LinkAccountSubtype["ROTH_401K"] = "roth 401k";
    LinkAccountSubtype["ROTH"] = "roth";
    LinkAccountSubtype["RRIF"] = "rrif";
    LinkAccountSubtype["RRSP"] = "rrsp";
    LinkAccountSubtype["SARSEP"] = "sarsep";
    LinkAccountSubtype["SEP_IRA"] = "sep ira";
    LinkAccountSubtype["SIMPLE_IRA"] = "simple ira";
    LinkAccountSubtype["SIPP"] = "sipp";
    LinkAccountSubtype["STOCK_PLAN"] = "stock plan";
    LinkAccountSubtype["TFSA"] = "tfsa";
    LinkAccountSubtype["THRIFT_SAVINGS_PLAN"] = "thrift savings plan";
    LinkAccountSubtype["TRUST"] = "trust";
    LinkAccountSubtype["UGMA"] = "ugma";
    LinkAccountSubtype["UTMA"] = "utma";
    LinkAccountSubtype["VARIABLE_ANNUITY"] = "variable annuity";
})(LinkAccountSubtype || (LinkAccountSubtype = {}));
export var LinkAccountVerificationStatus;
(function (LinkAccountVerificationStatus) {
    LinkAccountVerificationStatus["PENDING_AUTOMATIC_VERIFICATION"] = "pending_automatic_verification";
    LinkAccountVerificationStatus["PENDING_MANUAL_VERIFICATION"] = "pending_manual_verification";
    LinkAccountVerificationStatus["MANUALLY_VERIFIED"] = "manually_verified";
})(LinkAccountVerificationStatus || (LinkAccountVerificationStatus = {}));
export var LinkExitMetadataStatus;
(function (LinkExitMetadataStatus) {
    LinkExitMetadataStatus["CONNECTED"] = "connected";
    LinkExitMetadataStatus["CHOOSE_DEVICE"] = "choose_device";
    LinkExitMetadataStatus["REQUIRES_CODE"] = "requires_code";
    LinkExitMetadataStatus["REQUIRES_CREDENTIALS"] = "requires_credentials";
    LinkExitMetadataStatus["REQUIRES_EXTERNAL_ACTION"] = "requires_external_action";
    LinkExitMetadataStatus["REQUIRES_OAUTH"] = "requires_oauth";
    LinkExitMetadataStatus["REQUIRES_QUESTIONS"] = "requires_questions";
    LinkExitMetadataStatus["REQUIRES_RECAPTCHA"] = "requires_recaptcha";
    LinkExitMetadataStatus["REQUIRES_SELECTIONS"] = "requires_selections";
    LinkExitMetadataStatus["REQUIRES_DEPOSIT_SWITCH_ALLOCATION_CONFIGURATION"] = "requires_deposit_switch_allocation_configuration";
    LinkExitMetadataStatus["REQUIRES_DEPOSIT_SWITCH_ALLOCATION_SELECTION"] = "requires_deposit_switch_allocation_selection";
})(LinkExitMetadataStatus || (LinkExitMetadataStatus = {}));
export var LinkErrorCode;
(function (LinkErrorCode) {
    // ITEM_ERROR
    LinkErrorCode["INVALID_CREDENTIALS"] = "INVALID_CREDENTIALS";
    LinkErrorCode["INVALID_MFA"] = "INVALID_MFA";
    LinkErrorCode["ITEM_LOGIN_REQUIRED"] = "ITEM_LOGIN_REQUIRED";
    LinkErrorCode["INSUFFICIENT_CREDENTIALS"] = "INSUFFICIENT_CREDENTIALS";
    LinkErrorCode["ITEM_LOCKED"] = "ITEM_LOCKED";
    LinkErrorCode["USER_SETUP_REQUIRED"] = "USER_SETUP_REQUIRED";
    LinkErrorCode["MFA_NOT_SUPPORTED"] = "MFA_NOT_SUPPORTED";
    LinkErrorCode["INVALID_SEND_METHOD"] = "INVALID_SEND_METHOD";
    LinkErrorCode["NO_ACCOUNTS"] = "NO_ACCOUNTS";
    LinkErrorCode["ITEM_NOT_SUPPORTED"] = "ITEM_NOT_SUPPORTED";
    LinkErrorCode["INVALD_UPDATED_USERNAME"] = "INVALD_UPDATED_USERNAME";
    LinkErrorCode["ITEM_NO_ERROR"] = "ITEM_NO_ERROR";
    LinkErrorCode["NO_AUTH_ACCOUNTS"] = "NO_AUTH_ACCOUNTS";
    LinkErrorCode["NO_INVESTMENT_ACCOUNTS"] = "NO_INVESTMENT_ACCOUNTS";
    LinkErrorCode["NO_INVESTMENT_AUTH_ACCOUNTS"] = "NO_INVESTMENT_AUTH_ACCOUNTS";
    LinkErrorCode["NO_LIABILITY_ACCOUNTS"] = "NO_LIABILITY_ACCOUNTS";
    LinkErrorCode["PRODUCTS_NOT_SUPPORTED"] = "PRODUCTS_NOT_SUPPORTED";
    LinkErrorCode["ITEM_NOT_FOUND"] = "ITEM_NOT_FOUND";
    LinkErrorCode["ITEM_PRODUCT_NOT_READY"] = "ITEM_PRODUCT_NOT_READY";
    // INSTITUTION_ERROR
    LinkErrorCode["INSTITUTION_DOWN"] = "INSTITUTION_DOWN";
    LinkErrorCode["INSTITUTION_NOT_RESPONDING"] = "INSTITUTION_NOT_RESPONDING";
    LinkErrorCode["INSTITUTION_NOT_AVAILABLE"] = "INSTITUTION_NOT_AVAILABLE";
    LinkErrorCode["INSTITUTION_NO_LONGER_SUPPORTED"] = "INSTITUTION_NO_LONGER_SUPPORTED";
    // API_ERROR
    LinkErrorCode["INTERNAL_SERVER_ERROR"] = "INTERNAL_SERVER_ERROR";
    LinkErrorCode["PLANNED_MAINTENANCE"] = "PLANNED_MAINTENANCE";
    // ASSET_REPORT_ERROR
    LinkErrorCode["PRODUCT_NOT_ENABLED"] = "PRODUCT_NOT_ENABLED";
    LinkErrorCode["DATA_UNAVAILABLE"] = "DATA_UNAVAILABLE";
    LinkErrorCode["ASSET_PRODUCT_NOT_READY"] = "ASSET_PRODUCT_NOT_READY";
    LinkErrorCode["ASSET_REPORT_GENERATION_FAILED"] = "ASSET_REPORT_GENERATION_FAILED";
    LinkErrorCode["INVALID_PARENT"] = "INVALID_PARENT";
    LinkErrorCode["INSIGHTS_NOT_ENABLED"] = "INSIGHTS_NOT_ENABLED";
    LinkErrorCode["INSIGHTS_PREVIOUSLY_NOT_ENABLED"] = "INSIGHTS_PREVIOUSLY_NOT_ENABLED";
    // BANK_TRANSFER_ERROR
    LinkErrorCode["BANK_TRANSFER_LIMIT_EXCEEDED"] = "BANK_TRANSFER_LIMIT_EXCEEDED";
    LinkErrorCode["BANK_TRANSFER_MISSING_ORIGINATION_ACCOUNT"] = "BANK_TRANSFER_MISSING_ORIGINATION_ACCOUNT";
    LinkErrorCode["BANK_TRANSFER_INVALID_ORIGINATION_ACCOUNT"] = "BANK_TRANSFER_INVALID_ORIGINATION_ACCOUNT";
    LinkErrorCode["BANK_TRANSFER_ACCOUNT_BLOCKED"] = "BANK_TRANSFER_ACCOUNT_BLOCKED";
    LinkErrorCode["BANK_TRANSFER_INSUFFICIENT_FUNDS"] = "BANK_TRANSFER_INSUFFICIENT_FUNDS";
    LinkErrorCode["BANK_TRANSFER_NOT_CANCELLABLE"] = "BANK_TRANSFER_NOT_CANCELLABLE";
    LinkErrorCode["BANK_TRANSFER_UNSUPPORTED_ACCOUNT_TYPE"] = "BANK_TRANSFER_UNSUPPORTED_ACCOUNT_TYPE";
    LinkErrorCode["BANK_TRANSFER_UNSUPPORTED_ENVIRONMENT"] = "BANK_TRANSFER_UNSUPPORTED_ENVIRONMENT";
    // SANDBOX_ERROR
    LinkErrorCode["SANDBOX_PRODUCT_NOT_ENABLED"] = "SANDBOX_PRODUCT_NOT_ENABLED";
    LinkErrorCode["SANDBOX_WEBHOOK_INVALID"] = "SANDBOX_WEBHOOK_INVALID";
    LinkErrorCode["SANDBOX_BANK_TRANSFER_EVENT_TRANSITION_INVALID"] = "SANDBOX_BANK_TRANSFER_EVENT_TRANSITION_INVALID";
    // INVALID_REQUEST
    LinkErrorCode["MISSING_FIELDS"] = "MISSING_FIELDS";
    LinkErrorCode["UNKNOWN_FIELDS"] = "UNKNOWN_FIELDS";
    LinkErrorCode["INVALID_FIELD"] = "INVALID_FIELD";
    LinkErrorCode["INCOMPATIBLE_API_VERSION"] = "INCOMPATIBLE_API_VERSION";
    LinkErrorCode["INVALID_BODY"] = "INVALID_BODY";
    LinkErrorCode["INVALID_HEADERS"] = "INVALID_HEADERS";
    LinkErrorCode["NOT_FOUND"] = "NOT_FOUND";
    LinkErrorCode["NO_LONGER_AVAILABLE"] = "NO_LONGER_AVAILABLE";
    LinkErrorCode["SANDBOX_ONLY"] = "SANDBOX_ONLY";
    LinkErrorCode["INVALID_ACCOUNT_NUMBER"] = "INVALID_ACCOUNT_NUMBER";
    // INVALID_INPUT
    // From above ITEM_LOGIN_REQUIRED = "INVALID_CREDENTIALS",
    LinkErrorCode["INCORRECT_DEPOSIT_AMOUNTS"] = "INCORRECT_DEPOSIT_AMOUNTS";
    LinkErrorCode["UNAUTHORIZED_ENVIRONMENT"] = "UNAUTHORIZED_ENVIRONMENT";
    LinkErrorCode["INVALID_PRODUCT"] = "INVALID_PRODUCT";
    LinkErrorCode["UNAUTHORIZED_ROUTE_ACCESS"] = "UNAUTHORIZED_ROUTE_ACCESS";
    LinkErrorCode["DIRECT_INTEGRATION_NOT_ENABLED"] = "DIRECT_INTEGRATION_NOT_ENABLED";
    LinkErrorCode["INVALID_API_KEYS"] = "INVALID_API_KEYS";
    LinkErrorCode["INVALID_ACCESS_TOKEN"] = "INVALID_ACCESS_TOKEN";
    LinkErrorCode["INVALID_PUBLIC_TOKEN"] = "INVALID_PUBLIC_TOKEN";
    LinkErrorCode["INVALID_LINK_TOKEN"] = "INVALID_LINK_TOKEN";
    LinkErrorCode["INVALID_PROCESSOR_TOKEN"] = "INVALID_PROCESSOR_TOKEN";
    LinkErrorCode["INVALID_AUDIT_COPY_TOKEN"] = "INVALID_AUDIT_COPY_TOKEN";
    LinkErrorCode["INVALID_ACCOUNT_ID"] = "INVALID_ACCOUNT_ID";
    // INVALID_RESULT
    LinkErrorCode["PLAID_DIRECT_ITEM_IMPORT_RETURNED_INVALID_MFA"] = "PLAID_DIRECT_ITEM_IMPORT_RETURNED_INVALID_MFA";
    // RATE_LIMIT_EXCEEDED
    LinkErrorCode["ACCOUNTS_LIMIT"] = "ACCOUNTS_LIMIT";
    LinkErrorCode["ADDITION_LIMIT"] = "ADDITION_LIMIT";
    LinkErrorCode["AUTH_LIMIT"] = "AUTH_LIMIT";
    LinkErrorCode["BALANCE_LIMIT"] = "BALANCE_LIMIT";
    LinkErrorCode["IDENTITY_LIMIT"] = "IDENTITY_LIMIT";
    LinkErrorCode["ITEM_GET_LIMIT"] = "ITEM_GET_LIMIT";
    LinkErrorCode["RATE_LIMIT"] = "RATE_LIMIT";
    LinkErrorCode["TRANSACTIONS_LIMIT"] = "TRANSACTIONS_LIMIT";
    // RECAPTCHA_ERROR
    LinkErrorCode["RECAPTCHA_REQUIRED"] = "RECAPTCHA_REQUIRED";
    LinkErrorCode["RECAPTCHA_BAD"] = "RECAPTCHA_BAD";
    // OAUTH_ERROR
    LinkErrorCode["INCORRECT_OAUTH_NONCE"] = "INCORRECT_OAUTH_NONCE";
    LinkErrorCode["OAUTH_STATE_ID_ALREADY_PROCESSED"] = "OAUTH_STATE_ID_ALREADY_PROCESSED";
})(LinkErrorCode || (LinkErrorCode = {}));
export var LinkErrorType;
(function (LinkErrorType) {
    LinkErrorType["BANK_TRANSFER"] = "BANK_TRANSFER_ERROR";
    LinkErrorType["INVALID_REQUEST"] = "INVALID_REQUEST";
    LinkErrorType["INVALID_RESULT"] = "INVALID_RESULT";
    LinkErrorType["INVALID_INPUT"] = "INVALID_INPUT";
    LinkErrorType["INSTITUTION_ERROR"] = "INSTITUTION_ERROR";
    LinkErrorType["RATE_LIMIT_EXCEEDED"] = "RATE_LIMIT_EXCEEDED";
    LinkErrorType["API_ERROR"] = "API_ERROR";
    LinkErrorType["ITEM_ERROR"] = "ITEM_ERROR";
    LinkErrorType["AUTH_ERROR"] = "AUTH_ERROR";
    LinkErrorType["ASSET_REPORT_ERROR"] = "ASSET_REPORT_ERROR";
    LinkErrorType["SANDBOX_ERROR"] = "SANDBOX_ERROR";
    LinkErrorType["RECAPTCHA_ERROR"] = "RECAPTCHA_ERROR";
    LinkErrorType["OAUTH_ERROR"] = "OAUTH_ERROR";
})(LinkErrorType || (LinkErrorType = {}));
export var LinkEventName;
(function (LinkEventName) {
    LinkEventName["CLOSE_OAUTH"] = "close_oauth";
    LinkEventName["ERROR"] = "error";
    LinkEventName["EXIT"] = "exit";
    LinkEventName["FAIL_OAUTH"] = "fail_oauth";
    LinkEventName["HANDOFF"] = "handoff";
    LinkEventName["MATCHED_CONSENT"] = "matched_consent";
    LinkEventName["MATCHED_SELECT_INSTITUTION"] = "matched_select_institution";
    LinkEventName["OPEN"] = "open";
    LinkEventName["OPEN_MY_PLAID"] = "open_my_plaid";
    LinkEventName["OPEN_OAUTH"] = "open_oauth";
    LinkEventName["SEARCH_INSTITUTION"] = "search_institution";
    LinkEventName["SELECT_INSTITUTION"] = "select_institution";
    LinkEventName["SUBMIT_CREDENTIALS"] = "submit_credentials";
    LinkEventName["SUBMIT_MFA"] = "submit_mfa";
    LinkEventName["TRANSITION_VIEW"] = "transition_view";
})(LinkEventName || (LinkEventName = {}));
export var LinkEventViewName;
(function (LinkEventViewName) {
    LinkEventViewName["CONNECTED"] = "CONNECTED";
    LinkEventViewName["CONSENT"] = "CONSENT";
    LinkEventViewName["CREDENTIAL"] = "CREDENTIAL";
    LinkEventViewName["ERROR"] = "ERROR";
    LinkEventViewName["EXIT"] = "EXIT";
    LinkEventViewName["LOADING"] = "LOADING";
    LinkEventViewName["MFA"] = "MFA";
    LinkEventViewName["NUMBERS"] = "NUMBERS";
    LinkEventViewName["RECAPTCHA"] = "RECAPTCHA";
    LinkEventViewName["SELECT_ACCOUNT"] = "SELECT_ACCOUNT";
    LinkEventViewName["SELECT_INSTITUTION"] = "SELECT_INSTITUTION";
})(LinkEventViewName || (LinkEventViewName = {}));
